#coding:utf8
from django.contrib.contenttypes.models import ContentType

DEFAULT_HOMEPAGE_COVER = 'img/homepage_message.png'
DEFAULT_INTRO_COVER = 'img/intro_message.png'
DEFAULT_BUSINESS_COVER = 'img/business_message.png'
DEFAULT_NEWS_COVER = 'img/news_message.png'
DEFAULT_PRODUCT_COVER = 'img/product_message.png'
DEFAULT_CASE_COVER = 'img/case_message.png'
DEFAULT_WEIBO_COVER = 'img/weibo_message.png'
DEFAULT_CONTACT_COVER = 'img/kefuphone_message.png'
DEFAULT_JOIN_COVER = 'img/joinus_message.png'
DEFAULT_HELP_COVER = 'img/help_message.png'
DEFAULT_CONTENT_COVER = 'img/content_message.png'
DEFAULT_LINK_COVER = 'img/link_message.png'
DEFAULT_FINDME_COVER = 'img/findme_message.png'
DEFAULT_TRENDITEM_COVER = 'img/default_trenditem_cover.png'
DEFAULT_COVER = "img/empty.png"

DEFAULT_HOMEPAGE_MSG = u'点击查看%s微官网。'
DEFAULT_INTRO_MSG = u'点击查看公司介绍。'
DEFAULT_BUSINESS_MSG = u'点击查看公司业务。'
DEFAULT_NEWS_MSG = u'点击查看公司动态。'
DEFAULT_CASE_MSG = u'点击查看公司案例。'
DEFAULT_PRODUCT_MSG = u'点击查看公司产品。'
DEFAULT_WEIBO_MSG = u'点击查看公司官方微博。'
DEFAULT_CONTACT_MSG = u'点击查看公司联系方式。'
DEFAULT_JOIN_MSG = u'点击查看公司最新招聘信息。'
DEFAULT_HELP_MSG = u'点击查看新手指导。'
DEFAULT_MSG = "点击查看全部内容。"

DEFAULT_INTRO_ICON = 'themes/%s/home_intro.png'
DEFAULT_BUSINESS_ICON = 'themes/%s/home_business.png'
DEFAULT_NEWS_ICON = 'themes/%s/home_news.png'
DEFAULT_PRODUCT_ICON = 'themes/%s/home_product.png'
DEFAULT_CASE_ICON = 'themes/%s/home_case.png'
DEFAULT_WEIBO_ICON = 'themes/%s/home_weibo.png'
DEFAULT_CONTACT_ICON = 'themes/%s/home_contact.png'
DEFAULT_JOIN_ICON = 'themes/%s/home_joinus.png'
DEFAULT_HELP_ICON = 'themes/%s/home_help.png'
DEFAULT_ICON = 'themes/%s/default.png'