from django.conf.urls.defaults import *

urlpatterns = patterns('microsite.siteviews',
    url(r'homepage/(?P<item_id>\d+)', 'homepage'),
    url(r'intro/(?P<item_id>\d+)', 'intro'),
    url(r'business/(?P<item_id>\d+)', 'business'),
    url(r'trend/(?P<item_id>\d+)', 'trend'),
    url(r'team/(?P<item_id>\d+)', 'team'),
    url(r'teamitem/(?P<item_id>\d+)', 'teamitem'),
    url(r'trenditem/(?P<item_id>\d+)', 'trenditem'),
    url(r'join/(?P<item_id>\d+)', 'join'),
    url(r'joinitem/(?P<item_id>\d+)', 'joinitem'),
    url(r'weibo/(?P<item_id>\d+)', 'weibo'),
    url(r'link/(?P<item_id>\d+)', 'link'),
    url(r'case/(?P<item_id>\d+)/(?P<class_id>\d+)', 'case'),
    url(r'case/(?P<item_id>\d+)', 'case'),
    url(r'caseitem/(?P<item_id>\d+)', 'caseitem'),
    url(r'contact/(?P<item_id>\d+)', 'contact'),
    url(r'telephone/(?P<item_id>\d+)', 'telephone'),
    url(r'product/(?P<item_id>\d+)/(?P<class_id>\d+)', 'product'),
    url(r'product/(?P<item_id>\d+)', 'product'),
    url(r'productitem/(?P<item_id>\d+)', 'productitem'),
    url(r'help/(?P<item_id>\d+)', 'help'),
    url(r'content/(?P<item_id>\d+)', 'content'),
    url(r'pic', 'pic'),
    url(r'contact_map/(?P<item_id>\d+)/(?P<cur_lat>\d+(.(\d+)){0,1})/(?P<cur_lng>\d+(.(\d+)){0,1})', 'contact_map'),

)
